version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/ItemsPlanning.Pn/ItemsPlanning.Pn"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/ItemsPlanning.Pn/ItemsPlanning.Pn.Test"
  schedule:
    interval: daily